### ISSUE TITLE
Keys duplicated when typing quickly

### ISSUE THREAD

**Issue by Ape** [kimmoli/tohkbd2#11]
There are often some duplicated characters when typing quickly. I think this is not caused by key repeat because this happens even if you set the repeat delays really high.

Steps to reproduce (version 0.1.2):
1. Set repeat delay and rate to as high as possible for easier testing
2. Do the following actions quickly:
   - Press down F => F is emitted as expected
   - Press down J => another F is emitted instead of J (bug)
   - Release F => the expected J from the previous step is emitted now
   - Release J => nothing happens as expected

**Comment by kimmoli** [comment]
Relates to #10 which was not completely fixed.

**Comment by kimmoli** [comment]
And yes, this is caused by the logic used to decode key-events from the i2c device.
Working on this.

**Comment by kimmoli** [comment]
@Ape can you check this with 0.1.6.1 ?

**Comment by Ape** [comment]
Yes, this is fixed. Thanks.
