### ISSUE TITLE
Screen upside down when using the "right-tilted" keyboard connector

### ISSUE THREAD

**Issue by jwalck** [kimmoli/tohkbd2#12]
The screen always rotates +90 degrees, meaning it works when having the phone rotated to the left, but not to the right. Mounting the keyboard the other way (useful since TOHKBD otherwise covers the camera flash) and the screen gets locked upside down.

The software should detect which connector is used, and rotate accordingly.

**Comment by kimmoli** [comment]
Won't fix. Jolla orientation knows only Landscape, not reverse Landscape. 
Clear Force Landscape setting from tohkbd2 settings if want to use in reverse landscape.

**Comment by jwalck** [comment]
Interesting, did not know that given that the dynamic setting can turn most applications both ways.

If we can tell which connector is used, couldn't the force landscape option only be enforced for "normal" Landscape? I see no use in having a setting that forces the keyboard and screen to face opposite directions.:)

**Comment by kimmoli** [comment]
i'm actually waiting jolla to give me option "both landscapes" .. so just block portrait modes.

**Comment by jwalck** [comment]
Sounds resonable. Then this is a wait-for-someone-else-bug so closing it for now. Thanks for the information!
