### ISSUE TITLE
Missing key mappings

### ISSUE THREAD

**Issue by jwalck** [kimmoli/tohkbd2#16]
There are still a few mappings missing, here's a list! (The keys I list are as they are seen on the Scandic keyboard)
- sym-i - { - left brace
- sym-o - } - right brace
- sym-k - [ - left bracket
- sym-l - ] - right bracket
- sym-, - < - left crocodile (currently mapped to shift-,)
- sym-. - > - right crocodile (currently mapped to shift-.)
- sym-g - ' - apostrophe (the front-leaning one)
- sym-d - £ - pound sign
- sym-c - € - euro sign
- sym-m - µ - greek mu/micro

Pretty sure these are localisation related:
- sym-x - " - quote (currently on shift-ä)
- sym-a - ; - semi colon (currently on ö)
- sym -z - : - colon (currently on shift-ö)
- sym-å - + - plus sign (currently on shift-=)
- sym-ö - ( - left parenthesis (currently on shift-9)
- sym-ä - ) - right parenthesis (currently on shift-0)

Those that currently have no mapping are for me the highest priority, with braces and brackets going before £€µ.:)

**Comment by jwalck** [comment]
I notice that two key mappings are solved in 0.1.7.6, < / > are now mapped to sym-, / sym-. They're still mapped to shift-, / shift-. as well but I don't see this as an issue. Updated/current list:

| mod | key | mappiing | description | comment | implemented |
| --- | --- | --- | --- | --- | --- |
| sym | i | { | left brace |  | yes |
| sym | o | } | right brace |  | yes |
| sym | k | [ | left bracket |  | yes |
| sym | l | ] | right bracket |  | yes |
| sym | g | ' | apostrophe | (the front-leaning one) | N/A in US-PC105 |
| sym | d | £ | pound sign |  | N/A in US-PC105 |
| sym | c | € | euro sign |  | N/A in US-PC105 |
| sym | m | µ | greek mu/micro |  | N/A in US-PC105 |

Pretty sure these are localisation related:

| mod | key | mappiing | description | comment | implemented |
| --- | --- | --- | --- | --- | --- |
| sym | x | " | quote | (currently on shift-ä) | yes |
| sym | a | ; | semi colon | (currently on ö) | yes |
| sym | z | : | colon | (currently on shift-ö) | yes |
| sym | å | + | plus sign | (currently on shift-=) | yes |
| sym | ö | ( | left parenthesis | (currently on shift-9) | yes |
| sym | ä | ) | right parenthesis | (currently on shift-0) | yes |

**Comment by kimmoli** [comment]
![img_20150612_223511](https://cloud.githubusercontent.com/assets/4472660/8179763/754a939a-1421-11e5-8b50-2bd3d37cca8b.jpg)

**Comment by kimmoli** [comment]
Implemented what-ever is possible

**Comment by jwalck** [comment]
Was there a problem with the apostrophe? The ' or in combination with a char like é. sym-g is still unmapped anyway. Also µ, € and £ are still missing though that's not such a big deal for me.

Writing this mostly for future reference, #16 can still be considered done. Great job!

EDIT: Woops just saw your comments in the table. nevermind!:)
