### ISSUE TITLE
Suggestion: Add an option to double click for sticky keys

### ISSUE THREAD

**Issue by sakustar** [kimmoli/tohkbd2#22]
UX improvement.
// in finnish:
Sticky keyt toimisivat järkevämmin, mikäli asetuksissa olisi säätömahdollisuus "paina 'n' kertaa to enable".  Nyt ne on helppo jättää/kytkeä vahingossa päälle.

**Comment by kimmoli** [comment]
Also suggested that shift could stick for one char if just pressed once, like the sticky-ctrl/alt/sym works now.

**Comment by kimmoli** [comment]
IMO this is now implemented
