### ISSUE TITLE
Lock screen when keyboard closed -option

### ISSUE THREAD

**Issue by kimmoli** [kimmoli/tohkbd2#29]
15:46 < euj_> would it be possible to have either a toggle or perhaps even as default that when you
              close/remove the keyboard it would have the same effect as pressing the power button?
15:47 < euj_> aka turn the screen off and lock the phone if you have instant locking configured

Maybe...

**Comment by spiiroin** [comment]
@kimmoli: turning display off when keyboard is closed is something that could be handled within mce too. currently the policy is to skip it if there is touch activity between keypad open & close -> that is not in anyway carved to stone and can be tweaked if necessary

**Comment by kimmoli** [comment]
MER#1321 opened for suggesting mce to implement these
