### ISSUE TITLE
 suggestions like with the virtual keyboards?

### ISSUE THREAD

**Issue by gerddie** [kimmoli/tohkbd2#50]
It would be nice if word suggestions are given like it is done with the virtual keyboards, and one should be able to select the language  independently from the keyboard layout. 

I don't know whether it is possible to tap into the resources used by the virtual keyboards to achieve this. Maybe it is possible to not add TOHKBD as a new keyboard and inject the keyboard events directly into the currently active virtual keyboard ... I have no idea about how to program for sailfish OS and documentation on this low level seems thin. 

Anyway, KUDOS for bringing TOHKBD to life.

**Comment by kimmoli** [comment]
In near future, the virtual keyboard will be completely hidden when physical keyboard attached (at least it is already implemented in Maliit, though not merged into Sailfish yet), so i'm not going to put lot of effort anything that relates to virtual keyboard things. Sorry.

**Comment by gerddie** [comment]
Well, I can understand this, but my proposal to somehow harness the virtual keyboard implementation was just based on my poor understanding on the actual implementation details. I still think that "suggestions" would still be a nice feature to save typing, regardless of how it is implemented, and if you could give me some hints where I would have the hooks to make this possible, I'd even look into this myself.

**Comment by kimmoli** [comment]
There might be multiple ways to do this. 
One could be making own QPlatformInputContextPlugin to show the suggestions on screen.
