### ISSUE TITLE
[5.18] Layout choice not taken into account in Android apps

### ISSUE THREAD

**Issue by ageru** [kimmoli/tohkbd2#58]
# Steps to reproduce
1. Run SFOS 1.1.9.28, tohkbd2 0.5.18 (latest from Jolla store), use AZERTY keyboard
2. Set the keyboard layout to the French one in the tohkbd2 app
3. Write in a native Jolla app (mail, Messaging, tohkbd2 repeat rate test field...), and observe the layout is indeed the French one
4. Install an Android app, launch it, and write something inside it
# Actual result

The keyboard layout in the Android app appears to be QWERTY. Leaving the Android app to write in a native Jolla app, the layout remains the selected French one.
# Expected result

The layout selected should be reflected in Android apps.
# Note

This was not an issue for me with 0.4.2 (previous version in Jolla store), in both SFOS 1.1.7 & 1.1.9

**Comment by kimmoli** [comment]
Unfortunately there is nothing i can do for this. This is completely on Jolla side.

In 0.4.2 and 1.1.7.x everything was US, so this was not visible. Now Sailfish supports more layouts, but the Android comes behind, and has only US support.

There is one workaround out there, FAQ updated:

https://together.jolla.com/question/96836/tohkbd-faq/#96836-q22-why-selected-layout-is-not-working-in-android-apps

**Comment by ageru** [comment]
Hi Kimmoli,

Many thanks for your answer. I didn't expect this was what caused the issue, but it totally makes sense after reading your explanation.

I've noticed that in the case of the AZERTY layout, there's an additional Generic.kl file included in the archive. From my testing, it needs to be put in /opt/alien/system/usr/keylayout/ for the magic to happen. There's already a Generic.kl file in that folder that will of course need to be backuped as well. But once that's done, I can confirm it works as far as I can see. It's definitely good to have until they roll out a new alien update.

By the way, looking at the spanish archive, there's an es_latin.kl file that probably needs to go to that same folder for the spanish layout to work too.

In any case, many, many thanks again. I'll close the bug, since there's a workaround and the fix has to come from Jolla :)

(By the way, you might want to remove/edit [Q16 in the FAQ](https://together.jolla.com/question/96836/tohkbd-faq/#96836-q16-i-want-to-use-fingerterm-in-position-where-keyboard-does-not-block-flash-but-it-wont-turn-why), it doesn't look like it's relevant any more...)

**Comment by kimmoli** [comment]
Ok, thanks for the info. 

FAQs Q16, Q22 updated.
