### ISSUE TITLE
Error 107 when connecting keyboard

### ISSUE THREAD

**Issue by benna86** [kimmoli/tohkbd2#6]
Hi, my keyboard does not work: i receive the error
"tca8424: readInputReport failed, wrote -1, expected 6: Transport endpoint is not connected (107)"
anytime I connect the keyboard to the base.
Any idea about what it can be?

Thanks

Here the full message:

[root@Jolla ~]# systemctl status tohkbd
tohkbd.service - The Other Half QWERTY Keyboard
   Loaded: loaded (/etc/systemd/system/tohkbd.service; enabled)
   Active: active (running) since Wed 2015-04-08 08:36:32 CEST; 12h ago
 Main PID: 698 (tohkbd)
   CGroup: /system.slice/tohkbd.service
           └─698 /usr/sbin/tohkbd
...
Apr 08 20:41:28 Jolla tohkbd[698]: enabling tohkbd
Apr 08 20:41:28 Jolla tohkbd[698]: VDD control request - turn on
Apr 08 20:41:28 Jolla tohkbd[698]: VDD state already on
Apr 08 20:41:28 Jolla tohkbd[698]: Interrupt control request - turn on
Apr 08 20:41:28 Jolla tohkbd[698]: Interrupt state already on
Apr 08 20:42:48 Jolla tohkbd[698]: tca8424: readInputReport failed, wrote -1, expected 6: Transport endpoint is not connected (107)

**Comment by kimmoli** [comment]
The log you provided smells like tohkbd rev1 stuff, not tohkbd2.
Have you built this from sources, or installed from somewhere?

**Comment by benna86** [comment]
Hi,
I followed the instructions and added the repo http://repo.merproject.org/obs/home:/kimmoli:/tohs/sailfish_latest_armv7hl
then I installed tohkbd because harbour-tohkbd2 was not there.
Should I compile it from source instead?

**Comment by kimmoli** [comment]
there is harbour-ambience-tohkbd2

**Comment by benna86** [comment]
that worked! thanks!
