### ISSUE TITLE
Show "layout not available" error message also when connecting keyboard

### ISSUE THREAD

**Issue by xkr47** [kimmoli/tohkbd2#61]
After upgrading to 1.1.9.x, I browsed the Settings app for new settings and configured the hardware keyboard layout to "Swedish". Only later I upgraded software from jolla store (including TOHKBD2). I was a bit confused at first when keyboard did not respond at all (except for "Keyboard connected"). I then found out by accident after visiting the TOHKBD app (which greys out unsupported layouts) that the layout is not supported. I also later discovered that tohkbd shows a nice error message if an unsupported layut is selected, both in the TOHKBD app and the Settings app.

Yet I think it would be good to remind the user also when connecting the keyboard if an unsupported layout is currently selected to avoid unnecessary confusion.

**Comment by kimmoli** [comment]
See also 607d44347e1b3084d89af1f191bf0b71e98251b7

**Comment by xkr47** [comment]
Thanks!
