### ISSUE TITLE
Backslash and pipe key are not working in Finnish layout

### ISSUE THREAD

**Issue by Ape** [kimmoli/tohkbd2#64]
Almost every key seems to be working as expected, but `sym-B` for `|` produces `<` and `sym-N` for `\` produces `+`.  This is with Finnish keymap.

These are working properly when I switch to English keymap.

Sailfish 2.0.0.10 and tohkbd 0.5.23.

**Comment by kimmoli** [comment]
See following link:
https://together.jolla.com/question/96836/tohkbd-faq/#96836-q24-why-some-of-the-keys-are-not-working-properly-i-cant-type-or

**Comment by kimmoli** [comment]
If that does not help, from tohkbd-settings, tap on layouts and tap on restore original layouts (palauta alkuperäiset...) and retry.
