### ISSUE TITLE
TOHKBD2 no longer works after 2.1.0.9 upgrade

### ISSUE THREAD

**Issue by ummon29** [kimmoli/tohkbd2#66]
The TOHKBD2 is no longer detected after the 2.1.0.9 Early Access Update of SailfishOS.
I had no time for further debugging yet.
Found the corresponding thread on together.jolla.com:
https://together.jolla.com/question/156410/tohkbd2-no-longer-works-after-2109-upgrade/

Thank you for your great work.
Best Regards

**Comment by kimmoli** [comment]
tohkbd2 required rebuilding against 2.1.0.9 target. You can manually install up-to-date version directly from this link

http://repo.merproject.org/obs/home:/kimmoli:/tohs/sailfishos_2.1.0.9/armv7hl/harbour-ambience-tohkbd2-0.5.23-78.1.armv7hl.rpm

There are no actual changes.

It will be updateable through harbour after 2.1.0.x goes public.
