### ISSUE TITLE
Partially typing first part of word with screen keyboard and second with TOHKBD swaps parts

### ISSUE THREAD

**Issue by xkr47** [kimmoli/tohkbd2#69]
So if I

1. Write "Foo" in e.g. People app in "First name" field
2. Then attach the TOHKBD
3. Continue the word with "Bar", thus now having "FooBar" in the field
4. Make the field lose focus (switch to another field, submit the form, etc)
5. Notice how the word being edited changed to "BarFoo"

(Sailfish 2.1.0.11)

**Comment by kimmoli** [comment]
doh

**Comment by kimmoli** [comment]
There is propably nothing i can do about this 'feature'

**Comment by xkr47** [comment]
Yeah I guess the built-in keyboard might be to blame.. Workaround is not to use built in keyboard, or, to just write BarFoo instead :)
